Repository MinJeung-Kim/Team-Project, pull requests merged in 2021-03, with the labels that each got.

#1 main-index
  Nike.com/README.md
  Nike.com/cart.html
  Nike.com/css/cart.css
  Nike.com/css/common.css
  Nike.com/css/footer.css
  Nike.com/css/header.css
  Nike.com/css/main.css
  Nike.com/footer.html
  Nike.com/header.html
  Nike.com/index.html
Labels: 개발 시작

#4 상품상세페이지 1차 - 사진정렬
  Nike.com/css/detail.css
  Nike.com/css/footer.css
  Nike.com/css/main.css
  Nike.com/detail.html
  Nike.com/img/details/1a53cd39-f09e-4daa-9137-321124228fa9_primary.jpg
  Nike.com/img/details/1f748124-06f1-4d96-bbf6-4f64246c50d6_6 (1).jpg
  Nike.com/img/details/1f748124-06f1-4d96-bbf6-4f64246c50d6_6.jpg
  Nike.com/img/details/2a7d4293-68ac-409d-8e9d-c23ec9e1f1a9_primary (1).jpg
  Nike.com/img/details/2a7d4293-68ac-409d-8e9d-c23ec9e1f1a9_primary.jpg
  Nike.com/img/details/2e0ecc3b-681a-45bc-9e03-29da51d3ee0c_primary (1).jpg
  Nike.com/img/details/2e0ecc3b-681a-45bc-9e03-29da51d3ee0c_primary (2).jpg
  Nike.com/img/details/2e0ecc3b-681a-45bc-9e03-29da51d3ee0c_primary.jpg
  Nike.com/img/details/2f954103-679a-479a-8bc8-ec7636d958e4_primary.jpg
  Nike.com/img/details/333f1a83-144b-4db6-8b5d-ec3675b23c03_primary.jpg
  Nike.com/img/details/4022ab1a-191c-4561-8318-3731afcf95fc_primary (1).jpg
  Nike.com/img/details/4022ab1a-191c-4561-8318-3731afcf95fc_primary.jpg
  Nike.com/img/details/4339fef7-329d-442c-b011-7b62d7307031_3 (1).jpg
  Nike.com/img/details/4339fef7-329d-442c-b011-7b62d7307031_3.jpg
  Nike.com/img/details/58b98661-8040-45be-8b01-bf9ed1cfcd6e_primary.jpg
  Nike.com/img/details/5ee5da3e-6ff3-4126-81e9-02e99238865f_8 (1).jpg
  Nike.com/img/details/5ee5da3e-6ff3-4126-81e9-02e99238865f_8.jpg
  Nike.com/img/details/67cc65c6-f30a-439c-85aa-3a0fbdde836d_4 (1).jpg
  Nike.com/img/details/67cc65c6-f30a-439c-85aa-3a0fbdde836d_4.jpg
  Nike.com/img/details/7760f89c-2f01-4647-b0a6-d2beb5d6fa13_primary.jpg
  Nike.com/img/details/94be7bdc-0b73-40d3-a269-04083db4f859_primary.jpg
  Nike.com/img/details/CV0994-600_CV0994-600_primary-1 (1).jpg
  Nike.com/img/details/CV0994-600_CV0994-600_primary-1.jpg
  Nike.com/img/details/a10281f4-98c7-4349-8ddd-19aa85308832_9 (1).jpg
  Nike.com/img/details/a10281f4-98c7-4349-8ddd-19aa85308832_9.jpg
  Nike.com/img/details/aac.gif
  Nike.com/img/details/b94bb7d5-51c9-4bf9-9ec4-2e9275e8fff9_primary.jpg
  Nike.com/img/details/bb1bf666-aa4d-4c8e-9a07-b8749f74ef8c_5 (1).jpg
  Nike.com/img/details/bb1bf666-aa4d-4c8e-9a07-b8749f74ef8c_5.jpg
  Nike.com/img/details/bl_dot.png
  Nike.com/img/details/collect.gif
  Nike.com/img/details/colorwheel-thin.svg
  Nike.com/img/details/d5e30fdf-994a-40c8-b5a1-88eaef4ed96d_7 (1).jpg
  Nike.com/img/details/d5e30fdf-994a-40c8-b5a1-88eaef4ed96d_7.jpg
  Nike.com/img/details/dc_pre_CKOar8mHou8CFcnDlgodg3oBog_src_6371193_type_invmedia_cat_bgg6iwxz_dc_lat__dc_rdid__tag_for_ch.gif
  Nike.com/img/details/e821fe0a-4bf0-4a18-9d7a-3682656596bb_2 (1).jpg
  Nike.com/img/details/e821fe0a-4bf0-4a18-9d7a-3682656596bb_2.jpg
  Nike.com/img/details/e8ef11af-9a0b-4e6d-af2d-1c2127cf3e00_primary.jpg
  Nike.com/img/details/escrow_43x43_gray.png
  Nike.com/img/details/f04b28e6-d523-445a-bc80-aed3d98f2fde_primary.jpg
  Nike.com/img/details/f5f101cd-e6bf-4ea2-92cd-559b31577ef4_primary.jpg
  Nike.com/img/details/f79f0f6a-45d5-49c8-90e3-3e2b0941e95d_primary.jpg
  Nike.com/img/details/icon-sameday.png
  Nike.com/img/details/icon-star.jpg
  Nike.com/img/details/icon.png
  Nike.com/img/details/m.gif
  Nike.com/img/details/no-image.jfif
  Nike.com/img/details/preloader.gif
  Nike.com/img/details/s09898679282166.gif
  Nike.com/img/details/track (1).gif
  Nike.com/img/details/track (2).gif
  Nike.com/img/details/track.gif
Labels: 리뷰 요청

#10 관리자 - 대시보드
  Nike.com/admin-dashboard.html
  Nike.com/css/dashboard.css
  Nike.com/header.html
  Nike.com/src/dashboard.js
Labels: 개발 진행 중, 리뷰 요청

#18 관리자 - 주문관리
  Nike.com/admin-orderMng.html
  Nike.com/css/orderMng.css
  Nike.com/data/csscomb.json
  Nike.com/src/grid.js
Labels: 개발 진행 중, 리뷰 요청

#21 사용자 - 메인
  Nike.com/README.md
  Nike.com/cart.html
  Nike.com/css/cart.css
  Nike.com/css/header.css
  Nike.com/css/index.css
  Nike.com/header.html
  Nike.com/inCart.html
  Nike.com/index.html
  Nike.com/src/header.js
Labels: 개발 진행 중

#14 사용자-상품 상세 페이지
  Nike.com/css/detail.css
  Nike.com/detail.html
Labels: 개발 진행 중, 리뷰 요청

#24 관리자 UI-상품관리
  Nike.com/css/product_manage.css
  Nike.com/data/csscomb.json
  Nike.com/product_manage.html
Labels: 개발 진행 중, 리뷰 요청

#6 회원가입 페이지 재수정 했습니다.
  Nike.com/css/join.css
  Nike.com/join.html
Labels: 개발 진행 중, 리뷰 요청

#23 사용자 리뷰게시판
  Nike.com/css/review.css
  Nike.com/review.html
Labels: 개발 진행 중, 리뷰 요청

#20 관리자 게시판관리 페이지
  Nike.com/adminboard.html
  Nike.com/css/adminboard.css
  Nike.com/src/grid.js
Labels: 개발 진행 중

#7 로그인 페이지 수정본입니다
  Nike.com/css/login.css
  Nike.com/header.html
  Nike.com/login.html
  Nike.com/src/login_modal.js
Labels: 개발 진행 중, 리뷰 요청

#15 관리자-고객관리 페이지입니다.
  Nike.com/admin-customer-detail.html
  Nike.com/admin-customer.html
  Nike.com/category.html
  Nike.com/css/categorypage.css
  Nike.com/css/customer-detail.css
  Nike.com/css/customer.css
  Nike.com/src/script.js
Labels: 개발 진행 중, 리뷰 요청

#22 사용자 UI - 여성 카테고리
  Nike.com/category-w.html
  Nike.com/category.html
  Nike.com/css/categorypage.css
  Nike.com/css/customer.css
  Nike.com/img/w.category/w01.jpg
  Nike.com/img/w.category/w010.jpg
  Nike.com/img/w.category/w02.jpg
  Nike.com/img/w.category/w03.jpg
  Nike.com/img/w.category/w04.jpg
  Nike.com/img/w.category/w05.jpg
  Nike.com/img/w.category/w06.jpg
  Nike.com/img/w.category/w07.jpg
  Nike.com/img/w.category/w08.jpg
  Nike.com/img/w.category/w09.jpg
  Nike.com/img/w.category/w11.jpg
  Nike.com/img/w.category/w12.jpg
  Nike.com/img/w.category/w13.jpg
  Nike.com/img/w.category/w14.jpg
  Nike.com/img/w.category/w15.jpg
  Nike.com/img/w.category/w16.jpg
  Nike.com/img/w.category/w17.jpg
  Nike.com/img/w.category/w18.jpg
  Nike.com/img/w.category/w19.jpg
  Nike.com/img/w.category/w20.jpg
  Nike.com/img/w.category/w21.jpg
  Nike.com/img/w.category/w22.jpg
  Nike.com/img/w.category/w23.jpg
  Nike.com/img/w.category/w24.jpg
  Nike.com/img/w.category/w25.jpg
  Nike.com/img/w.category/w26.jpg
  Nike.com/img/w.category/w28.jpg
  Nike.com/img/w.category/w29.jpg
  Nike.com/img/w.category/w30.jpg
  Nike.com/img/w.category/w31.jpg
  Nike.com/img/w.category/w32.jpg
  Nike.com/img/w.category/w33.jpg
  Nike.com/img/w.category/w34.jpg
  Nike.com/img/w.category/w35.jpg
  Nike.com/img/w.category/w36.jpg
  Nike.com/img/w.category/w37.jpg
  Nike.com/img/w.category/w38.jpg
  Nike.com/img/w.category/w39.jpg
  Nike.com/src/category.js
Labels: 개발 진행 중

#29 관리자 고객 관리-수정
  .vscode/settings.json
  Nike.com/admin-customer-detail.html
  Nike.com/admin-customer.html
  Nike.com/css/customer-detail.css
  Nike.com/css/customer.css
  Nike.com/css/modal-detail.css
  Nike.com/img/img.category/s1.jpg
  Nike.com/img/img.category/s2.jpg
  Nike.com/img/img.category/s3.jpg
  Nike.com/src/category.js
  Nike.com/src/detail-modal.js
  Nike.com/src/script.js
Labels: 개발 진행 중, 리뷰 요청

#28 관리자 - 주문관리
  Nike.com/admin-dashboard.html
  Nike.com/admin-menu-common.html
  Nike.com/admin-orderMng.html
  Nike.com/css/orderMng.css
  Nike.com/header.html
  Nike.com/src/order-datePicker.js
  Nike.com/src/order-grid.js
Labels: 개발 진행 중, 리뷰 요청

#30 게시물 작성 모달창
  Nike.com/css/reviewform.css
  Nike.com/reviewform.html
Labels: 개발 진행 중

#31 회원가입 페이지
  Nike.com/css/join.css
  Nike.com/join.html
  Nike.com/src/join.js
Labels: 개발 진행 중, 리뷰 요청

#32 리뷰페이지
  Nike.com/css/review.css
  Nike.com/review-more.html
  Nike.com/review.html
  Nike.com/src/review.js
Labels: 개발 진행 중, 리뷰 요청

#49 [관리자] 주문관리 페이지 - 금액 설정 슬라이더
  Nike.com/admin-dashboard.html
  Nike.com/admin-menu-common.html
  Nike.com/admin-orderMng.html
  Nike.com/css/admin-dashboard.css
  Nike.com/css/admin-orderMng.css
  Nike.com/data/order-data.json
  Nike.com/src/admin-dashboard-canvas.js
  Nike.com/src/admin-dashboard-chart.js
  Nike.com/src/admin-dashboard.js
  Nike.com/src/admin-orderMng-grid.js
  Nike.com/src/admin-orderMng.js
  Nike.com/src/comm-date.js
  Nike.com/src/order-datePicker.js
  Nike.com/src/order-grid.js
Labels: 개발 완료, 리뷰 요청

#41 회원가입페이지
  Nike.com/src/join.js
Labels: 개발 진행 중

#47 [사용자] 리뷰 페이지 - 필터 js 구현
  Nike.com/css/review.css
  Nike.com/review-more.html
  Nike.com/review.html
  Nike.com/src/review.js
Labels: 개발 진행 중

#40 [관리자]고객 등록창
  Nike.com/admin-customer.html
  Nike.com/css/admin-customer-modal.css
  Nike.com/src/admin-customer.js
Labels: 개발 진행 중

#55 [사용자]상품상세페이지
  Nike.com/css/detail.css
  Nike.com/css/header.css
  Nike.com/css/search.css
  Nike.com/detail.html
  Nike.com/header.html
  Nike.com/src/detail.js
  Nike.com/src/search.js
Labels: 개발 진행 중, 리뷰 요청
