Repository MinJeung-Kim/Team-Project, pull requests merged in 2021-04, with the labels that each got.

#65 [관리자] 고객 등록 - 이름 유효성 검사
  src/main/resources/static/src/comm-validate.js
Labels: 개발 진행 중, 리뷰 요청

#67 [사용자] 카테고리 페이지 - 이미지 마우스오버, 메뉴 펼치기 구현
  src/main/resources/static/category.html
  src/main/resources/static/css/category.css
  src/main/resources/static/src/category.js
Labels: 개발 진행 중, 리뷰 요청, 배포 승인 + 2

#68 [사용자] 리뷰페이지-공지사항
  src/main/resources/static/css/review.css
  src/main/resources/static/notice.html
  src/main/resources/static/review.html
  src/main/resources/static/src/review-notice.js
Labels: 개발 진행 중, 배포 승인 + 2

#84 [사용자] 상품상세페이지 - 사이즈선택&수량제한 영역
  src/main/resources/static/css/detail.css
  src/main/resources/static/detail.html
  src/main/resources/static/src/detail.js
Labels: 개발 완료, 배포 승인 + 2

#83 [사용자] 상품상세페이지 - 리뷰영역
  src/main/resources/static/css/detail.css
  src/main/resources/static/detail.html
  src/main/resources/static/src/detail.js
Labels: 개발 진행 중, 리뷰 요청

#117 [사용자] 상품 상세 페이지 - 리뷰영역
  src/main/resources/static/src/detail.js
Labels: 개발 완료, 배포 승인 + 2

#109 [관리자] 대시보드 - 레이아웃 변경
  src/main/resources/static/admin-dashboard.html
  src/main/resources/static/css/admin-dashboard.css
  src/main/resources/static/src/comm-admin-menu.js
Labels: 개발 완료, 배포 승인 + 2

#101 [사용자] 회원가입페이지 - 전화번호 유효성검사 수정
  src/main/resources/static/join.html
  src/main/resources/static/src/join.js
Labels: 개발 완료, 배포 승인 + 2

#105 [관리자] 게시판 관리 페이지 - 공통 폼 적용
  src/main/resources/static/admin-board.html
  src/main/resources/static/css/admin-board.css
  src/main/resources/static/src/admin-board-modal.js
  src/main/resources/static/src/admin-board.js
Labels: 개발 완료, 배포 승인 + 2

#121 [사용자] 리뷰페이지/리뷰작성페이지 모달 연결
  src/main/resources/static/css/review-form.css
  src/main/resources/static/detail.html
  src/main/resources/static/src/reviewform.js
Labels: 개발 진행 중, 배포 승인 + 2

#132 [사용자] 상품상세페이지 - 서브이미지로 컬러 선택
  src/main/resources/static/css/detail.css
  src/main/resources/static/detail.html
  src/main/resources/static/img/details/440f95ef-7184-4874-bcb6-a3c22ee47819_primary.jpg
  src/main/resources/static/img/details/7ba466c7-365b-404a-9f17-141b92b96069_primary.jpg
Labels: 개발 완료, 리뷰 요청, 배포 승인 + 1

#134 Revert "[사용자] 상품상세페이지 - 서브이미지로 컬러 선택"
  src/main/resources/static/css/detail.css
  src/main/resources/static/detail.html
  src/main/resources/static/img/details/440f95ef-7184-4874-bcb6-a3c22ee47819_primary.jpg
  src/main/resources/static/img/details/7ba466c7-365b-404a-9f17-141b92b96069_primary.jpg
Labels: 오류 발생

#136 [사용자] 리뷰페이지 - 모달 연결
  src/main/resources/static/css/review-form.css
  src/main/resources/static/css/review.css
  src/main/resources/static/detail.html
  src/main/resources/static/review-more.html
  src/main/resources/static/src/review.js
Labels: 개발 완료, 배포 승인 + 2

#148 [관리자] 고객 관리페이지 - 등록 모달창 DB연결
  src/main/java/nike/shoppingmall/controller/CustomerController.java
  src/main/java/nike/shoppingmall/domain/Customer.java
  src/main/java/nike/shoppingmall/repository/CustomerRepository.java
  src/main/java/nike/shoppingmall/repository/JdbcCustomerRepository.java
  src/main/java/nike/shoppingmall/service/CustomerService.java
  src/main/resources/static/src/admin-customer-grid.js
  src/main/resources/static/src/admin-customer.js
  src/main/resources/static/src/comm-validate.js
  src/main/resources/templates/customer.html
Labels: 개발 완료, 리뷰 요청

#96 [관리자] 주문관리 - 주문상세 팝업
  src/main/resources/static/admin-orderMng.html
  src/main/resources/static/category.html
  src/main/resources/static/css/admin-orderMng-popup.css
  src/main/resources/static/css/admin-orderMng.css
  src/main/resources/static/css/category.css
  src/main/resources/static/css/common.css
  src/main/resources/static/src/admin-orderMng-grid.js
  src/main/resources/static/src/admin-orderMng-popup.js
  src/main/resources/static/src/admin-orderMng.js
  src/main/resources/static/src/category.js
Labels: 개발 완료, 리뷰 요청, 배포 승인 + 2

#94 [관리자] 주문관리 - 상단 메뉴, 사이드 메뉴
  src/main/resources/static/admin-orderMng.html
  src/main/resources/static/css/admin-orderMng.css
  src/main/resources/static/src/admin-orderMng.js
Labels: 개발 완료, 리뷰 요청, 배포 승인 + 2

#154 [사용자] 회원가입 페이지 - 회원가입 기능
  src/main/java/nike/shoppingmall/controller/CustomerController.java
  src/main/java/nike/shoppingmall/repository/CustomerRepository.java
  src/main/java/nike/shoppingmall/repository/JdbcCustomerRepository.java
  src/main/java/nike/shoppingmall/service/CustomerService.java
  src/main/resources/static/comm-header.html
  src/main/resources/static/join.html
  src/main/resources/static/src/join.js
Labels: 개발 완료, 배포 승인 + 2
